// action-types.ts
export enum ActionTypes {
  GET_EVENTLIST = "GET_EVENTLIST",
  SELECT_EVENT = "SELECT_EVENT",
  REMOVE_SELECTED_EVENT = "REMOVE_SELECTED_EVENT",
  MAKE_EVENT_UNSELECTABLE = "MAKE_EVENT_UNSELECTABLE",
  REMOVE_ERROR_STATE = "REMOVE_ERROR_STATE",
  ADD_ERROR = "ADD_ERROR",
}